name: Claim

on:
  push:
    branches: ["mainu"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [1]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        git clone https://github.com/akasakaid/grassxd
        cd grassxd
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        sed '1i2p8qpuKlYpcsiFEZjaBup7lSWxx' userid.txt
        echo "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkJseGtPeW9QaWIwMlNzUlpGeHBaN2JlSzJOSEJBMSJ9.eyJ1c2VySWQiOiIycDhxcHVLbFlwY3NpRkVaamFCdXA3bFNXeHgiLCJlbWFpbCI6ImJpbnRhbmVtYWlsQGdtYWlsLmNvbSIsInNjb3BlIjoiVVNFUiIsImlhdCI6MTczMjE1OTAxNSwibmJmIjoxNzMyMTU5MDE1LCJleHAiOjE3NjMyNjMwMTUsImF1ZCI6Ind5bmQtdXNlcnMiLCJpc3MiOiJodHRwczovL3d5bmQuczMuYW1hem9uYXdzLmNvbS9wdWJsaWMifQ.XsdRA3FDT1jT36U3Dh-btZtTsxxX2MQYb21GQUEJXdaIMdDCr-Y-xFN7nHqUKVdiMsMtTrGAUuGh0NKH49-iZO1OypTvMhZCQC0JeogO6tneXWocmyFX4895bv7gpflMhgtHhHST_WHTG6HrZK87Vxq0lO2PwOvtEZv5QRHhsG6s1xSIeY8pUHunAevhR_755a_7zpzj6ZEGSM-rF-M62bcOrWKGmPzIWWljlyijCv6PU0GUHeW_HknwibJlVcbA1S_SJtHMYGfxwQlUQ8ow4a091ygj89A9ykb7ZoYLv4IR2AK4Nd3PvMo86cM0eNgZjUvBG8AG08Dqpkss3dgMfw" > ./token.txt
        cat userid.txt
        ls -la
    - name: done
      run: exit
